name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Java & Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip tar

      - name: Cache Godot and Templates
        uses: actions/cache@v3
        with:
          path: |
            godot
            ~/.local/share/godot/export_templates/4.4.1.stable
          key: godot-4.4.1-${{ hashFiles('*.tpz', '*.zip') }}

      - name: Download Godot 4.3.1 Headless
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          unzip Godot_v4.4.1-stable_linux.x86_64.zip godot
          chmod +x godot

      - name: Download Android Export Templates
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget --tries=3 --waitretry=5 https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.3.1-stable_export_templates.tpz -O templates.tpz || \
          wget --tries=3 --waitretry=5 https://downloads.tuxfamily.org/godotengine/4.3.1/Godot_v4.4.1-stable_export_templates.tpz -O templates.tpz || { echo "Download failed from all mirrors"; exit 1; }
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          tar -xvf templates.tpz -C ~/.local/share/godot/export_templates/4.4.1.stable

      - name: Restore Keystore
        run: |
          echo "$KEYSTORE_B64" | base64 --decode > mykeystore.jks

      - name: Debug Environment
        run: |
          ls -la
          java -version
          ./godot --version

      - name: Build APK
        run: |
          ./godot --headless --export-release "Android" LifeLink_$(date +%Y%m%d_%H%M).apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lifelink-apk
          path: "*.apk"
