name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk wget unzip

      - name: Download Godot 4.4.1
        run: wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip

      - name: Unzip Godot
        run: unzip Godot_v4.4.1-stable_linux.x86_64.zip

      - name: Rename Godot executable
        run: mv Godot_v4.4.1-stable_linux.x86_64 Godot

      - name: Make Godot executable
        run: chmod +x Godot

      - name: Download Android export templates
        run: |
          wget https://downloads.tuxfamily.org/godotengine/export_templates/4.4.1/Godot_v4.4.1-stable_export_templates.tpz
          unzip Godot_v4.4.1-stable_export_templates.tpz -d ~/.local/share/godot/templates/4.4.1/

      - name: Decode keystore
        run: |
          echo "$KEYSTORE_B64" | base64 -d > mykeystore.jks

      - name: Build APK
        run: |
          ./Godot --headless --export "Android" "builds/Lifelink.apk" --sign "mykeystore.jks" "$KEYSTORE_PASSWORD" "$KEY_ALIAS" "$KEY_PASSWORD"

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lifelink-APK
          path: builds/Lifelink.apk
